config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dreams#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :dreams do
    resources :bookings, only: [:index, :show, :new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: :destroy

  patch "bookings/:id/accept", to: "bookings#accept", as: :accept
  patch "bookings/:id/decline", to: "bookings#decline", as: :decline
  get "/dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dream
  enum status: { pending: 0, accepted: 1, decline: 2 }
  validates :reservation_date, presence: true
end

app/models/dream.rb
class Dream < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [:title, :description],
  associated_against: {
    user: [:username]
  },
  using: {
    tsearch: { prefix: true }
  }

  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_one_attached :picture

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  DREAM_CATEGORIES = [
    "Aventure",
    "Surréaliste",
    "Fantastique",
    "Relaxant",
    "Mystère",
    "Romance",
    "Nostalgie",
    "Exploration",
    "Immersion"
  ]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :dream
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :dreams
  has_many :reviews
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_dream, only: [:new, :create]


  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.dream = @dream
    @booking.save
    redirect_to dashboard_path()
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path()
  end

  def accept
    @booking = Booking.find(params[:id])
    @dream = Dream.find(@booking.dream.id)
    @booking.accepted!
    redirect_to dashboard_path()
  end

  def decline
    @booking = Booking.find(params[:id])
    @dream = Dream.find(@booking.dream.id)
    @booking.decline!
    redirect_to dashboard_path()
  end

  private

  def booking_params
    params.require(:booking).permit(:reservation_date, :user_id, :dream_id)
  end

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @dreams = Dream.global_search(params[:query])
    elsif params[:category].present?
      @dreams = Dream.where(category: params[:category])
    else
      @dreams = Dream.all
    end

    @markers = @dreams.geocoded.map do |dream|
      {
        lat: dream.latitude,
        lng: dream.longitude,
        info_window_html: render_to_string(partial: "dreams/info_window", locals: { dream: dream }, formats: :html),
        marker_html: render_to_string(partial: "dreams/marker", formats: :html)
      }
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @dream = Dream.find(params[:id])
    @booking = Booking.new
    @reviews = Review.all
    @review = Review.new
  end

  def new
    @dream = Dream.new
  end

  def create
    @user = current_user
    @dream = Dream.new(dream_params)
    @dream.user_id = @user.id
    @dream.save
    redirect_to dashboard_path()
  end

  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dashboard_path()
  end

  private

  def dream_params
    params.require(:dream).permit(:title, :description, :picture, :category, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @dreams = @user.dreams
    @allbookings = Booking.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_dream
  def create
    @review = @dream.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @dream, notice: 'Review was successfully created.'
    else
      render 'dreams/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :user_id, :dream_id)
  end

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<h1>Booking</h1>

<%= @booking.dream.title %>
<%= @booking.reservation_date %>

app/views/bookmarks/show.html.erb
<h1>Booking</h1>

<%= @booking.dream.title %>

app/views/dreams/_dream.html.erb
<%  if (dream.picture.attached?) %>
  <div class="dreamcard">
    <img class="dreamcard-image" src="<%= cl_image_path dream.picture.key %>" alt="">
    <div class="dreamcard-info">
      <p class="tag"> <%= dream.category %> </p>
      <h2> <%= dream.title %> </h2>
      <p> <%= dream.description.truncate(100, separator: ' ') %> </p>
      <div class="dreamcard-price">
        <p class="price"><%= number_with_precision(dream.price, precision: 2, separator: ".") %>€</p>
        <p>/nuit</p>
      </div>
      <%= link_to "Voir le rêve", dream_path(dream), class: "button" %>
    </div>
  </div>
<% else %>
  <div class="dreamcard">
    <img class="dreamcard-image" src="#" alt="">
    <div class="dreamcard-info">
      <h2> <%= dream.title %> </h2>
      <div class="dreamcard-tags">
        <p class="tag"> <%= dream.category %> </p>
      </div>
      <p class="dreamcard-text"> <%= dream.price %> </p>
      <%= link_to "Voir le rêve", dream_path(dream), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/dreams/_info_window.html.erb
<%= link_to dream_path(dream), class: "text-decoration-none" do %>
  <div>
    <img class="dreamcard-image mb-0 no-rounded-bot" src="<%= cl_image_path dream.picture.key %>" alt="">
    <div class= "py-2">
      <h2 class="no-margin text-white fs-5"><%= dream.title %></h2>
      <p class="no-margin text-white fs-8"><%= dream.address %></p>
      <p class="no-margin text-white fs-8"><%= number_with_precision(dream.price, precision: 2, separator: ".") %>€</p>
    </div>
  </div>
<% end %>

app/views/dreams/_list.html.erb
<% if dreams.any? %>
  <% dreams.each do |dream| %>
    <%= render "dreams/dream", dream: dream %>
  <% end %>
<% else %>
  <div>
    <p class="no-margin">Désolé, pas de rêves trouvés.</p>
  </div>
<% end %>

app/views/dreams/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/dreams/index.html.erb
<div class="position-relative">
  <!-- HERO BANNER -->
  <div class="hero-banner">
    <div class="hero-content">
      <h1 class="title">Louez un rêve pour la nuit,<br>plongez dans l’inconnu.</h1>
      <p class="content">Et si cette nuit, vous choisissiez votre rêve ? Embarquez dans un<br>voyage onirique unique. Chaque nuit devient une nouvelle aventure.</p>
    </div>
  </div>
</div>

<div id="categories" data-controller="search">

  <!-- BARRE DE RECHERCHE -->
  <div class="search-container" data-controller="reset">
    <%= form_with url: dreams_path, method: :get, class: "d-flex search-form", data: { action: "click->search#fire", search_target: "form" } do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control search-input",
            style: "border: 0;",
            placeholder: "Tapez un mot-clé...",
            data: {
              reset_target: "textField",
              action: 'input->reset#changeInput'
            }
      %>
      <%= button_tag(type: 'button', data: { action: "click->reset#clear", reset_target: 'button' }, class: "button-close #{ 'd-none' if params[:query].blank? }") do %>
        <i class="fa-solid fa-x icon"></i>
      <% end %>
      <%= submit_tag "Recherche", name: "", class: "btn btn-search search-button" %>
    <% end %>
  </div>

  <!-- CATEGORY -->
  <div class="categories-container">
    <% Dream::DREAM_CATEGORIES.each do |category| %>
      <%= link_to dreams_path(category: category, anchor: "categories"), class: "text-decoration-none category #{ 'active' if params[:category] == category}" do %>
        <%= image_tag "categories/#{category.parameterize}.svg", alt: category  %>
        <p class="category-title"><%= category %></p>
      <% end %>
    <% end %>
  </div>

  <!-- DREAM LIST -->
  <div class="dreamcard-container" data-search-target="results">
    <%= render "dreams/list", dreams: @dreams %>
  </div>
</div>

<!-- CARTE -->
<div data-controller="toggle" class="mt-5 position-fixed" style="bottom: 20px; left: 0; right: 0;">
  <div class="d-flex justify-content-center">
    <button  data-action="click->toggle#fire" data-toggle-target="button" class="btn btn-map" style="z-index: 10;">Carte</button>
  </div>
  <div style="width: 100%; height: 100vh; position: fixed; top: 0; left: 0; z-index: 5"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-toggle-target="togglableElement" class="d-none">
  </div>
</div>

app/views/dreams/new.html.erb
<div class="container">
  <h1 class="text-white text-center mb-3">Ajoute un rêve !</h1>
  <div class="row">
    <div class="col text-white">
      <%= simple_form_for(@dream) do |f| %>
        <%= f.input :title, label: 'Titre', class:"input" %>
        <%= f.input :description, label: 'Description' %>
        <%= f.input :picture, as: :file, label: 'Photo' %>
        <%= f.input :category, collection: Dream::DREAM_CATEGORIES, label: 'Catégorie' %>
        <%= f.input :price, label: 'Prix' %>
        <div class="d-flex justify-content-center p-3">
          <%= f.submit 'Fais nous rêver', class: "button category active submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dreams/show.html.erb
<div class="row border-bottom border-light mb-3">
  <div class="col-6 border-end border-light pe-5 mb-5">
    <div class="detailed-container">
      <div class="row d-flex justify-content-center align-item-center">
        <div class="col-4">
          <div class="detailed-tag text-center">
            <h5 class="">Categorie : <%= @dream.category %></h5>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="image-container">
          <%  if @dream.picture.attached? %>
            <%= cl_image_tag @dream.picture.key, class: "detailed-image", crop: :fill %>
          <% else %>
            <%= image_tag 'johannes-plenio-DKix6Un55mw-unsplash.jpg', class: "detailed-image", alt: "bannière"  %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="detailed-info">
          <div class="">
            <h2><%= @dream.title %></h5>
          </div>
          <p class="card-text dreamcard-info text-justify"><%= @dream.description %></p>
          <div class="detailed-price">
            <p class=""><small class="text-body-secondary"><%= @dream.price %></small></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6 d-flex flex-column justify-content-between align-items-center">
    <div class="container d-flex flex-column justify-content-between align-items-center h-100">
      <div class="row flex-grow-1 d-flex justify-content-center align-items-center custom-margin-top">
        <div class="col text-white text-center">
          <%= simple_form_for [@dream, @booking] do |f| %>
            <%= f.input :reservation_date,
                        as: :string,
                        input_html: { data: { controller: "datepicker" }, class: "d-none", readonly: true },
                        label: 'Date de réservation', class: 'detailed-datepicker-title'%>
            <div class="d-flex justify-content-center">
              <%= f.submit "Réserve ton rêve !", class: "detailed-button"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div data-controller="review" class="">
  <div class="row d-flex justify-content-center mb-3">
    <div class="col-3 d-flex justify-content-center">
      <button class="detailed-button mb-3" data-action="click->review#fire">Ajoute un commentaire</button>
    </div>
  </div>

  <div class="row d-none" data-review-target="form">
    <div class="col text-white">
      <%= simple_form_for([@dream, @review]) do |f| %>
        <%= f.input :content, label: 'Contenu' %>
        <%= f.submit 'Commenter', class: "mb-3 detailed-button"%>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-white" style='background-color: #15161a;'>
      <% @dream.reviews.each do |review| %>
        <div class="row">
          <div class="col-6">
            <div class="card-product">
              <div class="card-product-infos border-top pt-3 pb-1">
                <h2><%= review.user.username %></h2>
                <p><%= review.content %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
  </head>

  <body>
    <!-- NAVBAR -->
    <%= render "shared/navbar" %>

    <!-- GLOBAL CONTAINER -->
    <div class="global-container">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>

    <!-- FOOTER -->
    <div class="footer">
      <%= image_tag "dreambnb.svg" %>
      <p>Louez un rêve pour la nuit.</p>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1 class="text-white fw-medium">Tableau de bord</h1>

<!-- PROFIL -->
<!--
<div class="profil-container">
  <div class="profil-card">
    <h3>Profil</h3>
    <%= current_user.picture %>
    <%= current_user.username %>
    <%= current_user.email %>
  </div>
  <div class="infos-card">
    <h3>Rêveur</h3>
    <%= current_user.bookings.count %>
  </div>
  <div class="infos-card">
    <h3>Vendeur de rêves</h3>
    <%= current_user.dreams.count %>
  </div>
</div>
 -->

<div class="d-flex">
  <!-- RÉVEUR -->
  <div class="infos-section">
    <h2 class="profil-title">Rêveur</h2>
    <!-- RÉSERVATION -->
    <div class="infos">
      <h3 class="profil-subtitle">Mes réservations</h3>
      <p >(<%= current_user.bookings.count %>)</p>
    </div>
    <div class="bookingcard-container" data-controller="buttonsvalidation">
    <% if @bookings.count.zero? %>
      <div class="bookingcard">
        <p>Pas de réservation</p>
      </div>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="bookingcard">
          <% if booking.status == "pending" %>
            <div class="tag pending">
              <p>En attente</p>
            </div>
          <% elsif booking.status == "accepted" %>
            <div class="tag accepted">
              <p>Validée</p>
            </div>
          <% elsif booking.status == "decline" %>
            <div class="tag decline">
              <p>Refusée</p>
            </div>
          <% end %>
          <h3><%= booking.dream.title %></h3>
          <div class="booking-date">
              <%= image_tag "date.svg" %>
              <%= booking.reservation_date %>
          </div>
          <%= link_to "Annuler réservation", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button"%>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>

  <%= image_tag "line.png", class: "line"%>

  <!-- VENDEUR DE RÊVE -->
  <div class="infos-section">
    <h2 class="profil-title">Marchand de rêve</h2>
    <!-- RÉSERVATION EN ATTENTE -->
    <div class="infos">
      <h3 class="profil-subtitle">Réservations de mes rêves</h3>
      <p>(<%= current_user.dreams.joins(:bookings).count %>)</p>
    </div>
    <div class="bookingcard-container" data-controller="buttonsvalidation">
      <% if current_user.dreams.joins(:bookings).count.zero? %>
        <div class="bookingcard">
          <p>Pas de réservation</p>
        </div>
      <% else %>
        <% @dreams.each do |dream| %>
          <% allbookings = dream.bookings %>
          <% allbookings.each do |booking| %>
            <% if booking.dream == dream && booking.status != "decline"%>
              <div class="bookingcard">
                <% if booking.status == "pending" %>
                  <div class="tag pending">
                    <p>En attente</p>
                  </div>
                <% elsif booking.status == "accepted" %>
                  <div class="tag accepted">
                    <p>Validée</p>
                  </div>
                <% elsif booking.status == "decline" %>
                  <div class="tag decline">
                    <p>Refusée</p>
                  </div>
                <% end %>
                <h3><%= dream.title %></h3>
                <div class="booking-user">
                  <%= image_tag "user.svg" %>
                  <%= User.find(booking.user_id).username %>
                </div>
                <div class="booking-date">
                  <%= image_tag "date.svg" %>
                  <%= booking.reservation_date %>
                </div>
                <div class="booking-buttons">
                  <% if booking.status == "pending" %>
                    <%= link_to "Valider", accept_path(booking), class: "booking-btn accept", data: { turbo_method: "PATCH" } %>
                    <%= link_to "Refuser", decline_path(booking), class: "booking-btn refuse", data: { turbo_method: "PATCH" } %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<hr>

<!-- RÊVES À LOUER -->
  <div class="infos">
    <h3 class="profil-title">Mes rêves</h3>
    <h3>(<%= current_user.dreams.count %>)</h3>
  </div>

  <div class="dreamcard-container">
    <% @dreams.each do |dream| %>
      <%  if (dream.picture.attached?) %>
        <div class="dreamcard">
          <img class="dreamcard-image" src="<%= cl_image_path dream.picture.key %>" alt="">
          <div class="dreamcard-info">
            <p class="tag"> <%= dream.category %> </p>
            <h2> <%= dream.title %> </h2>
            <p> <%= dream.description.truncate(100, separator: ' ') %> </p>
            <div class="dreamcard-price">
              <p class="price"><%= number_with_precision(dream.price, precision: 2, separator: ".") %>€</p>
              <p>/nuit</p>
            </div>
            <div class="dreamcard-buttons">
              <%= link_to "Voir le rêve", dream_path(dream), class: "button btn-view"%>
              <%= link_to dream_path(dream), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button btn-delete" do %>
                <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="dreamcard">
          <img class="dreamcard-image" src="#" alt="">
          <div class="dreamcard-info">
            <h2> <%= dream.title %> </h2>
            <div class="dreamcard-tags">
              <p class="tag"> <%= dream.category %> </p>
            </div>
            <p class="dreamcard-text"> <%= dream.price %> </p>
            <%= link_to "Voir le rêve", dream_path(dream), class: "btn btn-primary" %>
            <%= link_to "Supprimer", dream_path(dream), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="dreamcard-container">
  <div class="dreamcard">
    <img class="dreamcard-image" src="#" alt="">
    <div class="dreamcard-info">
       <h2>Title</h2>
      <div class="dreamcard-tags">
        <p class="tag">Tag 1</p>
        <p class="tag">Tag 2</p>
        <p class="tag">Tag 3</p>
      </div>
      <p class="dreamcard-text">2 crédits</p>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between align-items-center p-0">

    <!-- Logo à gauche -->
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "dreambnb.svg"%>
    <% end %>

    <%#<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <!-- Menu centré -->
     <div class="d-flex justify-content-center flex-grow-1">
        <ul class="gap-4 navbar-nav">
            <li class="nav-item active">
              <%= link_to "Louer un rêve", dreams_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "Ajouter un rêve", new_dream_path, class: "nav-link text-white" %>
            </li>
        </ul>
      </div>

      <!-- Menu utilisateur à droite -->
      <div class="d-flex ms-auto">
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown profil-size">
            <%  if (current_user.photo.attached?) %>
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              </a>
            <% else %>
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
              </a>
            <% end %>
              <i class="fa-solid fa-angle-down ms-2" style="color: #ffffff;"></i>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Tableau de bord", dashboard_path(), class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Connexion", new_user_session_path, class: "nav-link text-white connect" %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>
</div>